window.AIR_PURIFIER_MODEL = {
  profile: {
    schoolName: "Cedar Ridge Unified School District (Example)",
    adminName: "Dr. Elena Martinez",
    role: "Superintendent",
    location: "California",
  },
  controls: {
    minStudents: 200,
    maxStudents: 120000,
    step: 100,
    defaultStudents: 4800,
  },
  assumptions: {
    schoolDaysPerYear: 180,
    schoolDayHours: 6.5,
    studentAttendanceRate: 0.9,
    studentTeacherRatio: 15.2,
    baselineTeacherSickDaysPerYear: 5,
    baselineTeacherTotalAbsenceDaysPerYear: 9.4,
    purifierStudentAbsenceReductionPct: 0.125,

    // Modeled PM impact branch for teacher illness and behavior pressure.
    assumedBaselinePm25UgM3: 10,
    purifierPm25ReductionPct: 0.32,
    teacherIllnessAbsenceIncreasePer10UgPm25: 0.131,
    behaviorReferralIncreasePer10UgPm25: 0.28,

    sameDayTestScoreGainZ: 0.11,
    healthRelatedChronicAbsenceRate: 0.058,
    childAsthmaPrevalenceRate: 0.062,
  },
  assumptionRows: [
    {
      label: "Student attendance baseline",
      value: "90% daily attendance",
      source: "S5",
      confidence: "High",
    },
    {
      label: "Students per teacher",
      value: "15.2:1",
      source: "S6",
      confidence: "High",
    },
    {
      label: "Teacher sick days baseline",
      value: "5 sick days/teacher/year",
      source: "S7",
      confidence: "Medium",
    },
    {
      label: "Student absences with purifiers",
      value: "12.5% lower absenteeism",
      source: "S1",
      confidence: "High",
    },
    {
      label: "PM2.5 reduction with classroom HEPA",
      value: "32% reduction",
      source: "S2",
      confidence: "High",
    },
    {
      label: "Teacher illness sensitivity to PM2.5",
      value: "+13.1% illness absences per +10 ug/m3",
      source: "S3",
      confidence: "Medium",
    },
    {
      label: "Behavior referral sensitivity to PM2.5",
      value: "+28% referrals per +10 ug/m3",
      source: "S3",
      confidence: "Medium",
    },
    {
      label: "Same-day test score signal",
      value: "+0.11 SD with purifiers",
      source: "S4",
      confidence: "Medium",
    },
    {
      label: "Health-related chronic absenteeism",
      value: "5.8% of children",
      source: "S8",
      confidence: "High",
    },
    {
      label: "Childhood asthma prevalence",
      value: "6.2%",
      source: "S9",
      confidence: "High",
    },
  ],
  modelNotes: [
    "Student absenteeism reduction uses direct intervention evidence from an air purifier school trial.",
    "Teacher and behavior impacts are modeled from PM2.5 elasticities because direct teacher RCT estimates are still limited.",
    "Same-day test score uplift is from a randomized crossover purifier study; student K-12 transfer should be treated as directional.",
  ],
  sources: [
    {
      id: "S1",
      title: "The Effect of Air Purifiers in Schools",
      publisher: "Resources for the Future (Working Paper)",
      year: "2025",
      url: "https://www.rff.org/publications/working-papers/the-effect-of-air-purifiers-in-schools/",
      whyItMatters: "Randomized evidence: classroom purifiers reduced student absenteeism by 12.5%.",
    },
    {
      id: "S2",
      title:
        "Assessing the effects of portable air cleaners in California classrooms on indoor PM2.5 concentrations and asthma health",
      publisher: "Journal of Exposure Science & Environmental Epidemiology",
      year: "2025",
      url: "https://www.nature.com/articles/s41370-025-00743-9",
      whyItMatters: "Randomized trial evidence that portable classroom HEPA units materially lower PM2.5.",
    },
    {
      id: "S3",
      title: "The Effects of PM2.5 in Schools",
      publisher: "National Bureau of Economic Research (Working Paper 33549)",
      year: "2025",
      url: "https://www.nber.org/papers/w33549",
      whyItMatters:
        "Links PM2.5 to higher student absences, teacher illness absences, and discipline referrals in U.S. schools.",
    },
    {
      id: "S4",
      title: "Air pollution impairs cognitive performance but improved indoor air quality can help",
      publisher: "Environmental Science & Technology (PubMed)",
      year: "2024",
      url: "https://pubmed.ncbi.nlm.nih.gov/38647545/",
      whyItMatters: "Randomized crossover evidence: purifier use improved test performance by 0.11 SD.",
    },
    {
      id: "S5",
      title: "Public school leaders report 90% average daily student attendance rate",
      publisher: "NCES",
      year: "2024",
      url:
        "https://nces.ed.gov/learn/press-release/public-school-leaders-report-90-percent-average-daily-student-attendance-rate-november-2023",
      whyItMatters: "Provides baseline attendance for no-filtration scenario sizing.",
    },
    {
      id: "S6",
      title: "Public School Enrollment and Staff (2023-24)",
      publisher: "NCES CCD",
      year: "2024",
      url: "https://nces.ed.gov/ccd/tables/202324_summary_2.asp",
      whyItMatters: "Provides student-teacher ratio to estimate teacher counts from student counts.",
    },
    {
      id: "S7",
      title: "Roll Call 2020",
      publisher: "National Council on Teacher Quality",
      year: "2020",
      url: "https://www.nctq.org/research-insights/roll-call-2020/",
      whyItMatters: "Baseline for teacher sick leave assumptions (editable as local district data becomes available).",
    },
    {
      id: "S8",
      title: "Health-related school absenteeism among children and adolescents in the U.S.",
      publisher: "NCHS Data Brief 499 (CDC)",
      year: "2024",
      url: "https://www.cdc.gov/nchs/data/databriefs/db499.pdf",
      whyItMatters: "National benchmark for chronic absenteeism risk tied to health conditions.",
    },
    {
      id: "S9",
      title: "Most Recent National Asthma Data",
      publisher: "CDC",
      year: "2025",
      url: "https://www.cdc.gov/asthma-data/about/most-recent-asthma-data.html",
      whyItMatters: "Approximate share of students likely to be especially sensitive to poor indoor air quality.",
    },
    {
      id: "S10",
      title: "Health and Environmental Effects of Particulate Matter (PM)",
      publisher: "U.S. EPA",
      year: "2025",
      url: "https://www.epa.gov/pm-pollution/health-and-environmental-effects-particulate-matter-pm",
      whyItMatters: "PM2.5 exposure is linked to respiratory and cardiovascular harm, especially in vulnerable groups.",
    },
  ],
};
